commitizen:
  bump_message: "bump: [skip ci] release $current_version \u2192 $new_version"
  name: cz_conventional_commits
  tag_format: $version
  update_changelog_on_bump: true
  version: 0.6.0
  version_files:
  - VERSION
