version: 2.1

executors:
  alpine:
    docker: 
      - image: alpine:3.12
     
parameters:
  tag:
    type: string
    default: "<< pipeline.number >>.0"
    
commands:
  test:
    parameters:
      myparameter:
        type: string
        default: "crileroro"
    steps:
      - run: 
          name: Echoing message test
          command: echo "Hello <<parameters.myparameter>>"

jobs:  
  version-tag:
    executor: alpine
    steps:
      - run:
          name: test echo
          command: echo "This is the tag <<pipeline.parameters.tag>>"

  default:
    executor: alpine
    steps:
      - test
      
  job-1:
    executor: alpine
    steps:
      - test: 
          myparameter: "test-1"
          
  job-2:
    executor: alpine
    steps:
      - test: 
          myparameter: "test-2"
  
  job-3:
    executor: alpine
    steps:
      - test: 
          myparameter: "test-3"
         
workflows:
  feature-flow:
    jobs:
      - version-tag:
          <<: *feature_filter
      - validate-commits:
          <<: *feature_filter

  release-flow:
    jobs:
      - commitizen:
          requires:
            - validate-commits
          <<: *release_filter
