version: 2.1

commands:
  test:
    parameters:
      myparameter:
        type: string
        default: "crileroro"
    steps:
      - run: echo "Hello <<parameters.myparameter>>"

jobs:
  my-job:
    docker:
      - image: alpine:3.12
    steps:
      - test: 
          myparameter: "test-12345"
          
