version: 2.1

commands:
  test:
    parameters:
      myparameter:
        type: string
        default: "crileroro"
    steps:
      - run: echo "Hello <<parameters.myparameter>>"

jobs:
  job-1:
    docker:
      - image: alpine:3.12
    steps:
      - test: 
          myparameter: "test-1"
  job-2:
    docker:
      - image: alpine:3.12
    steps:
      - test: 
          myparameter: "test-2"
  job-3:
    docker:
      - image: alpine:3.12
    steps:
      - test: 
          myparameter: "test-3"
         
workflows:
  my-workflow-1:
    jobs:
      - job-1
      - job-2
  my-workflow-2:
    jobs:
      - job-3

