version: 2.1

commands:
  test:
    parameters:
      myparameter:
        type: string
        default: "crileroro"
    steps:
      - run: 
          name: Echoing message test
          command: echo "Hello <<parameters.myparameter>>"

jobs:
  docker:
      - image: alpine:3.12
      
  default:
    steps:
      - test
      
  job-1:
    steps:
      - test: 
          myparameter: "test-1"
          
  job-2:
    steps:
      - test: 
          myparameter: "test-2"
  
  job-3:
    steps:
      - test: 
          myparameter: "test-3"
         
workflows:
  my-workflow-1:
    jobs:
      - job-1
      - job-2:
          requires:
            - job-1
  my-workflow-2:
    jobs:
      - job-3
      - default

