version: 2.1

commands:
  test:
    parameters:
      myparameter:
        type: string
        default: "crileroro"
    steps:
      - run: echo "Hello <<parameters.myparameter>>"

jobs:
  build:
    docker:
      - image: alpine:3.12
    steps:
      - test: 
          myparameter: "test-12345"
          
# workflows:
#   my-workflow:
#     jobs:
#       - my-job
          
